AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - "lib/sqdash/cli.rb"
    - "lib/sqdash/renderer.rb"

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "lib/sqdash/cli.rb"
    - "lib/sqdash/renderer.rb"
    - "lib/sqdash/input_handler.rb"
    - "lib/sqdash/autocomplete.rb"

Metrics/ClassLength:
  Max: 300
  Exclude:
    - "lib/sqdash/cli.rb"

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - "lib/sqdash/renderer.rb"
    - "lib/sqdash/input_handler.rb"
    - "lib/sqdash/autocomplete.rb"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "lib/sqdash/cli.rb"
    - "lib/sqdash/renderer.rb"
    - "lib/sqdash/autocomplete.rb"

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - "lib/sqdash/cli.rb"
    - "lib/sqdash/autocomplete.rb"

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - "lib/sqdash/cli.rb"
    - "lib/sqdash/renderer.rb"
    - "lib/sqdash/autocomplete.rb"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "sqdash.gemspec"
